### ISSUE TITLE
Vlastní web pro PyLadies Praha

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#1]
@lspdv:

PyLadies Praha by měly mít vlastní web, oddělený od Brna, aktualizovaný dle toho, co se aktuálně dějě.

**Vyřešit:** Navrhnout web pro PyLadies Praha – již řeší @SvetlanaM, může přidat návrh? Související: https://github.com/PyLadiesCZ/pyladies/issues/25

**Comment by encukou** [comment]
Jak moc oddělený? Předpokládám že jde hlavně o [stránku s materiály](http://pyladies.cz/course.html); úvodní stránka může zůstat společná?

**Comment by lspdv** [comment]
Stranka zustane spolecna, jde o stranku sponzoru a materialu.

**Comment by lspdv** [comment]
Uvodni stranka muze zustat spolecna, ale informace o Praze budou jine. Materialy zrejme budou jinak sestavene, pokud se nam bude lepe delat had. Pote stranka sponzoru bude take jina v obsahu.

**Comment by asgeirrr** [comment]
Myslím, že nejpraktičtější by bylo mít kolekci všech materiálů na jednom místě. To zatím máme na http://pyladies.cz/course.html a to bych zachoval. Jen by pak byla jedna stránka s harmonogramem Brna a Prahy zvlášť, která se bude měnit podle aktuálně probíhajícího kurzu.

Myslím, že všichni máme tu představu, že na začátku je několik lekcí
se základy (cykly, testování, Git, ...), které se moc měnit nebudou a
pak budou ty, které se budou měnit podle toho, jaké je zrovna složení
konkrétního kurzu, nebo podle toho, co holky baví (např. když tam bude
5 holek, co dělá analýzu dat, tak zařadíme analýzu dat, jinak to
nedává smysl).

Dne Ne, 13. prosinec 2015 v 09:45 h uživatel Veronika napsal:

> Uvodni stranka muze zustat spolecna, ale informace o Praze budou jine.
> Materialy zrejme budou jinak sestavene, pokud se nam bude lepe delat
> had. Pote stranka sponzoru bude take jina v obsahu.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/PyLadiesCZ/documents/issues/1#issuecomment-164239440

**Comment by encukou** [comment]
Jojo, to je i moje představa – tady máš lekce, takhle to děláme my, ale poskládej si vlastní kurz :)
Zatím to existuje ve formě odboček dole.

**Comment by SvetlanaM** [comment]
![pp2](https://cloud.githubusercontent.com/assets/3219358/12378812/89968e44-bd4a-11e5-9525-6d088dde6421.png)
![pp3](https://cloud.githubusercontent.com/assets/3219358/12378813/89977d72-bd4a-11e5-9f4c-359c709c780a.png)

Bolo to myslené tak, že jedna hlavná úvodná všeobecná stránka o pyladies ako takých v čr s inform, navrchu je vždy skorolovateľné pohyblivé menu a možnosť vybrať mestá alebo materiály pre dané mestá, na stránke materiálov to chcem zautomatizovať javascriptom aby steto nemuseli robiť ručne a vždy v daný týždeň by bol preddefinovane nastaný a href na danú sekciu a stránka o meste je všeobecná špecifická pre to mesto, Veronika a jedným z jej návrhov bolo dať tam info ako to v tom meste vzniklo. Ale berte to ako prvy navrh, ak chcete niečo inak, specialne, alebo graficky inak tak mi to napiste viac detailnejsie, lebo to zatial robim bez grafickej predlohy rovno ako ma v hlavne napadne.

**Comment by SvetlanaM** [comment]
![fireshot capture 84 - pyladies cz - http___margetova eu_pylady_](https://cloud.githubusercontent.com/assets/3219358/12378846/4f66fd48-bd4b-11e5-9c60-9a6aa9e502ea.png)

**Comment by encukou** [comment]
\o/
Super! Vypadá to úžasně :)

Časem bude potřeba navrhnout design pro situace, kdy:
- je v jednom městě více pravidelných akcí (v Brně je kurz a srazy)
- potřebujeme dočasně propagovat nějakou událost na hlavní stránce (nový kurz, nové město, DjangoGirls workshop)

Graficky:
- Tenké čáry v seznamu materiálů bych vynechal
- Potřebujeme obrázky, kde mají hlavní roli PyLadies, ne koučové
- Pyvo je "Pyvo", ne ikonka
- Potřebujeme logo konkrétně pro PyLadies CZ :)

Doufám že stránka půjde vidět i bez Javascriptu (bez zvýraznění a aktuálního hrefu se noscripter obejde), ale to kdyžtak dodělám.

Plánuješ ten návrh dát na Github, aby se na tom dalo dál spolupracovat? :)

**Comment by lspdv** [comment]
- na logu PyladiesCZ pracuji, chtela bych za sebe dodat tri navrhy - aktualne mam v praci hotovy teprve jeden
- souhlasim, ze ikonka piva je matouci
- nesouhlasim ale, ze by na fotkach mely byt jen holky 1) zadne poradne fotky kde jsou jen holky aktualne nemame 2) si myslim, ze delat z toho porad tlakem jen holcici vec neni dobry napad a ani holky to samy tak nevidi 3) ze s tim kluci aktualne nejvice pomahaji je pravda a netajila bych to? 

Tesim se na dalsi navrhy, az si to spolecne projdeme zitra po PyLadies.

Bohuzel me zkouskove dost blokuje a nestihla jsem pripravit navrhy ceskych textu :-(( Kdyby kdokoliv mel prostor to udelat, tak to pripadne rada uvitam. 

Odesláno z iPadu
1. 1. 2016 v 11:49, Petr Viktorin notifications@github.com:

**Comment by encukou** [comment]
1) To by se mělo napravit; ale i fotky s nějakým koučem jsou v pohodě.
2) No, na to jsou to PyLadies; na obecné akce kolem Pythonu máme Pyvec. Spolupráce je samozřejmě vitaná :)
3) Já bych to taky netajil, třeba ta fotka jak jsou kolem PyLady koučové je super. Ale mít jako první věc na hlavní stránce fotku, kde jsu uprostřed já a kolem možná nějaké holky, s tím nesouhlasím.

**Comment by SvetlanaM** [comment]
oki :+1:  tak nafotime ako baby horlivo programuju

**Comment by SvetlanaM** [comment]
uz idem, po dnesku zapracujem vsetkych poznamky, fotky neboli vyberane cielene len tieto najviac sedeli pomerovo a boli nacentrovane

**Comment by SvetlanaM** [comment]
Spíšem to súhrnne zatiaľ sem:
1. Zapracujem ešte pred nahratím kódu na GitHub poznámky od vás z dneška

Čo som si spísala, že bude upravené:
1. Na úvodnej fotke prefarbiť TWISTO z trička
2. Pridať link na fotografa (niekam do footeru) - ak som to pochopila správne z toho emailu zo včera
3. Sekcia "Pre koho" na úvodnej stránke - vymeniť ikonku PyLadies
4. Nahradiť Ostravu na "Založ vlastný PyLady" 
5. Vymazať tú čiernu konzolu, namiesto toho dať sekciu s odkazom na materiály - pochopila som, že teda nejaké všeobecné, nie odlišné podľa miest. 
6. Upraviť logá
7. Pokračovať na Django Girls nahradiť za PyVo
8. Odstrániť spodnú časť prísť na PyVo
9. Pridať nadpis partneri
10. Detail kurzu - zrušiť čiary v tabuľke
11. V detaile mesta pridať možnosť stať sa PyLady - premyslím, kam to umiestniť
12. V detaile mesta pridať sekciu ak sa koná viac kurzov, zrazov - premyslím to
13. Pridať fotky koučov/organizátorov za každé mesto? - týmto soms i nie istá, či to bolo finálne schválené alebo nie

Čo by bolo treba asi od vás:
1. Skúsiť tú ikonku PyLadies nájsť v PNG formáte nevyfarbené. Pôsobí to tam dosť nejednotne ak sú všetky ikonky tenké, alebo zmeniť potom všetky ikonky za iné
2. Vyplniť linky na odkazy
3. Logá ak máte v nejakom originál formáte alebo si ich môžem stiahnuť z netu  a upraviť teda všetky
4. Myslím texty si asi budete editovať vy
5. Ak máte nejaké špeciálne fotky, ktoré chcete tak pošlite

**Comment by encukou** [comment]
0. Dát to na Github :)

**Comment by honzajavorek** [comment]
Čo som si spísala, že bude upravené:
- [x] Na úvodnej fotke prefarbiť TWISTO z trička
- [ ] Pridať link na fotografa (niekam do footeru) - ak som to pochopila správne z toho emailu zo včera ⇢ https://github.com/PyLadiesCZ/pyladies.cz/issues/5
- [x] Sekcia "Pre koho" na úvodnej stránke - vymeniť ikonku PyLadies (@honzajavorek: je super!)
- [x] Nahradiť Ostravu na "Založ vlastný PyLady"
- [x] Vymazať tú čiernu konzolu, namiesto toho dať sekciu s odkazom na materiály - pochopila som, že teda nejaké všeobecné, nie odlišné podľa miest.
- [x] Upraviť logá
- [x] Pokračovať na Django Girls nahradiť za PyVo
- [x] Odstrániť spodnú časť prísť na PyVo
- [x] Pridať nadpis partneri
- [x] Detail kurzu - zrušiť čiary v tabuľke
- [x] V detaile mesta pridať možnosť stať sa PyLady - premyslím, kam to umiestniť
- [x] V detaile mesta pridať sekciu ak sa koná viac kurzov, zrazov - premyslím to
- [x] Pridať fotky koučov/organizátorov za každé mesto? - týmto soms i nie istá, či to bolo finálne schválené alebo nie

Čo by bolo treba asi od vás:
1. Skúsiť tú ikonku PyLadies nájsť v PNG formáte nevyfarbené. Pôsobí to tam dosť nejednotne ak sú všetky ikonky tenké, alebo zmeniť potom všetky ikonky za iné
2. Vyplniť linky na odkazy ⇢ https://github.com/PyLadiesCZ/pyladies.cz/issues/14
3. Logá ak máte v nejakom originál formáte alebo si ich môžem stiahnuť z netu a upraviť teda všetky ⇢ https://github.com/PyLadiesCZ/pyladies.cz/issues/4
4. Myslím texty si asi budete editovať vy ⇢ https://github.com/PyLadiesCZ/pyladies.cz/issues/15
5. Ak máte nejaké špeciálne fotky, ktoré chcete tak pošlite

---

Rozhážu zbytek do jednotlivých issues na https://github.com/PyLadiesCZ/pyladies.cz/issues, ať se dají jedna po druhé řešit.

**Comment by honzajavorek** [comment]
> Skúsiť tú ikonku PyLadies nájsť v PNG formáte nevyfarbené. Pôsobí to tam dosť nejednotne ak sú všetky ikonky tenké, alebo zmeniť potom všetky ikonky za iné

Spolu se @zuzejk jsme se shodli, že tak jak je to teď je to nakonec úplně v pohodě :)

**Comment by lspdv** [comment]
To se bavime o ikonce vlevo nahore te psane a nebo hlava u "pro koho je kurz" prosim?

Odesláno z iPadu
1. 1. 2016 v 12:59, Honza Javorek notifications@github.com:

**Comment by honzajavorek** [comment]
Bavíme se o hlavě PyLady u "pro koho je kurz".
