### ISSUE TITLE
Solitaire změnit na jiný program

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#12]
@lspdv:

Bylo by dobré Solitaire Klondike změnit na jednodušší hru (Had, Lodě), či jiný prográmek, případně I nějaký, který by byl slečnám užitečný k práci s excelovými tabulkami apod. Většina koučů se shodla, že ntice by tam již být neměly, měla by být větší motivace k používání tříd.

**Vyřešit:** Je potřeba, aby se zpracování materiálů na novou hru někdo ujmul – tato procvičovací hra/program by měl splňovat předpoklad využití již probraných témat dle http://pyladies.cz/course.html:
1. Cykly
2. Funkce a řetězce
3. Testování
4. Seznamy

**Comment by encukou** [comment]
Mimochodem, v Brně by nám Solitaire vyšel s vánoční přestávkou, tak jsem před vánoci ukázal jak se řeší Had z domácích úkolů. (Tam n-tice jsou, ale jako páry souřadnic, tak jak se pak využívají i v praxi.) A myslím že to bylo docela fajn :)

**Comment by encukou** [comment]
V úkolech je teď šibenice a had, a na konci asteroidy.
