### ISSUE TITLE
Grafika – předpřipravit sekvenci 5 – 7 obrázků pro lekci grafiky

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#13]
@lspdv:

...něco co se bude hýbat – Ninja, tanečnice… - aby to holky více nadchlo

**Vyřešit:** Připravit obrázky pro lekci grafiky, dle zadání (dotazy na @zuzejk)

**Comment by encukou** [comment]
Dají se použít třeba věci z Liberated Pixel Cup (pod CC-BY-SA), jako http://opengameart.org/content/character-animations-clothes-armor-weapons-skeleton-enemy-combat-dummy
