### ISSUE TITLE
Vylepšit stávající Solitaire

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#14]
@lspdv:

Solitaire využijeme po skončení oficiálního běhu PyLadies jako pokračování pro holky – na schůzce se většina koučů shodla, že zpracovat Solitaire dohromady s grafikou by bylo zajimavé, holky by programovat hru Solitaire mohlo více nadchnout. 

**Vyřešit:** Přepracovat Solitaire s grafikou – naprogramovat tak, aby se využilo co nejvíce znalostí, méně n-tic, více motivovat k používání tříd

**Comment by encukou** [comment]
Solitaire nahradily piškvorky, had a asteroidy. Asteroidy mají míň *n*-tic a vic tříd.
