### ISSUE TITLE
Uspořádat lekce PyLadies

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#16]
@lspdv:

Na schůzce padly požadavky na přesunutí některých témat dál a jiných blíže. Byla bych ráda za názory a případné odhlasování a změnu.

**Vyřešit:**
- Navrhnout přesuny
- Odhlasovat je
- Změnit je v tabulce koučů
- Změnit je na webu PyLadies Praha

**Comment by encukou** [comment]
Přidávám štítek Praha; pro Brno tohle budu dělat v rámci každého běhu. (Někdy je řazení třeba i podle svátků/předpokládané účasti, a tak.)
Budu rád za připomínky k Brnu, ale nejradši v jiné Issue :)

**Comment by lspdv** [comment]
Souhlasim a dnes jsme to udelali! Muze se to tedy zavrit?

**Comment by encukou** [comment]
Jestli je to změněné v tabulce koučů a na webu PyLadies Praha, tak jo :)

Na http://pyladies.cz/course.html jsem vyměnil grafiku a slovníky. Myslím že další připomínky nebyly, můžeš to prosím pro jistotu porovnat se svýma poznámkama?

**Comment by lspdv** [comment]
Tak nic ;-) 

Odesláno z iPadu

17. 3. 2016 v 11:27, Petr Viktorin <notifications@github.com>:

**Comment by lspdv** [comment]
V poznamkach mam ze se skrta pong z Grafiky. Jdu se pustit do tabulky koucu Prahy ;-)

**Comment by lspdv** [comment]
[Tabulka koučů - aktualizováno po poradě](https://docs.google.com/spreadsheets/d/1VGmtDIyKCG89Dlo__Zq_AoEb6Raa1cJs_9P6Nwelejw/edit#gid=568131145)

@encukou a @asgeirrr , podle mých poznámek to vypadá takto, přičemž jsem měla v poznámkách slovníky jen 1x a pak si v tabulce z minula všimla, že byly Slovníky I a II. - bude to tak znovu, že?

:point_right:Tím se Asteroidy II v Praze posunuly až na první týden v červenci (prázdniny) takže to už bude pojaté formou pokračovacího kurzu, nicméně toto bych byla pro sdělit slečnám již při registraci, aby s tím mohly počítat

**Comment by encukou** [comment]
Já bych radši nechal jen Slovníky I (S Github API místo Twitteru je to jednodušší), a pak Asteroidy I a II, s tím že Asteroidy II se dají dát do pokračovacího kurzu operativně, kdyby se zase něco protáhlo.

Ale @asgeirrr může nesouhlasit :)

**Comment by lspdv** [comment]
Jelikož se mi zdá jako velká pravděpodobnost, že @asgeirrr bude slovníky v
Praze přednášet (protože je super!), tak se v tomto přikloním hlavně k jeho
slovu :-))

2016-03-18 17:13 GMT+01:00 Petr Viktorin notifications@github.com:

**Comment by asgeirrr** [comment]
Díky za tu chválu Verčo:) Osobně se mi líbilo to GitHub API, sice to není pro holky tak atraktivní, ale je to mnohem jednodušší. Jediné, co si nejsem jist je, zda se do jedné hodiny vejde vysvětlení slovníků, JSONu a příklad s Github API, ale je pravda, že @encukou zvládl v Praze ten GitHub dost rychle. Takže bych to udělal, jak říká.

Pořád se mi ten Twitter líbí, protože to má pěkný výstup a procvičí to
používání objektů, seznamů, slovníků i komunikaci přes nějaké API, což
je věc, která se holkám hodí, kdyby opravdu chtěli za nějakou dobu
zkusit pracovat jako programátorky. Nabídl bych jim to jako ten
pokračovací projekt. Jen by to pak chtělo upravit materiály, aby samy
vytáhly ta data z Twitteru, teď to měly v zájmu časové úspory jako
blackbox, což se mi moc nelíbilo. Rád to udělám, kdyby na to došlo.

@lspdv Koukal jsem na rozvrh pro Prahu a přijde mi to dobré. Je to v
podstatě to, na čem jsme se dohodli ve středu.

Dne Pá, 18. březen 2016 v 17:19 h uživatel Veronika napsal:

> Jelikož se mi zdá jako velká pravděpodobnost, že @asgeirrr bude
> slovníky v
> 
> Praze přednášet (protože je super!), tak se v tomto přikloním
> hlavně k jeho
> 
> slovu :-))
> 
> 2016-03-18 17:13 GMT+01:00 Petr Viktorin notifications@github.com:
> 
> Já bych radši nechal jen Slovníky I (S Github API místo Twitteru je to
> 
> jednodušší), a pak Asteroidy I a II, s tím že Asteroidy II se
> dají dát do
> 
> pokračovacího kurzu operativně, kdyby se zase něco protáhlo.
> 
> Ale @asgeirrr https://github.com/asgeirrr může nesouhlasit :)
> 
> —
> 
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> 
> https://github.com/PyLadiesCZ/documents/issues/16#issuecomment-198430797
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/PyLadiesCZ/documents/issues/16#issuecomment-198433039

**Comment by lspdv** [comment]
Dobře, nechme slovníky jen na jeden sraz, bude to lepší časově, díky!

Dne 20. března 2016 11:54 Oskar Hollmann notifications@github.com
napsal(a):
