### ISSUE TITLE
Vedlejší materiály - Interaktivní hry a knihy

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#17]
@lspdv:

Bylo by skvělé kdyby někdo začal dělat rešerši všech možných online her, výukových pomůcek a případně dobrých knih pro začátečníky okolo pythonu, ale třeba i Git apod.

**Vyřešit:** Sepsat dokument s možnostmi a odkazy na ně.

**Comment by honzajavorek** [comment]
Můj vlastní komentář k tomuto - jelikož jsou tyto věci zcela univerzálně použitelné, rád bych je dal spíš na python.cz do sekce pro začátečníky, aby to bylo pro všechny, co chtějí s Pythonem začít.

Něco už máme v připravované nové verzi webu: http://pythoncz-0375.rostiapp.cz/zacatecnici

**Comment by vahalova** [comment]
Zavírám, odkazy jsou na python.cz a dají se dál doplňovat....už to tu leží dlouho.
