### ISSUE TITLE
Poučit dopředu všechny kouče o desateru

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#2]
@lspdv:

V průběhu jsme zjistili, že i když si všichni přejeme přátelskou atmosféru, nemůže být na srazech chaos. Terka proto dala dohromady Desatero pro kouče, které teď zrovna nemohu najít. Důležité je hlavně nedělat práci za holky, pomáhat jim, ale nechat je na řešení přijít samy. Pak taky zajistit hlavnímu koučovi klid na práci a to jak ze strany vedlejších koučů, tak ze strany studentek.
- https://github.com/PyLadiesCZ/documents/blob/master/beginner-course/coach-manifest.md
- Související: https://github.com/PyLadiesCZ/pyladies/issues/15

**Comment by befeleme** [comment]
Rozhodnuto, ze se deseatero nezavedlo.
