### ISSUE TITLE
Změna procvičovací hry pro Prahu na Pong

### ISSUE THREAD

**Issue by lspdv** [PyLadiesCZ/documents#20]
Na prvním lednovém srazu PyLadies Praha, jsme vymýšleli, jak zkusit udělat procvičovací hru jinak, aby holky tentokrát případně tolik neodradila a ukázala jim, jak je programování fajn a zábavné.

Díky hlavně @SvetlanaM za objevení následujícího: http://python-alhindi.blogspot.cz/2013/11/game-pong.html 

Osobně si myslím, že by to holky mohlo bavit i vizuálně, vypadá to, že by se to případně dalo stihnout v dvouhodinovce a tím pádem vidět výsledky hned. Což je důležitá součást výuky! Pro koho? Pro mě třeba. :-)...by bývala byla!

Zároveň navrhuji menší posun v tabulce lekcí/koučů Prahy a to následovně:

1) (tabulka aktuálně: https://docs.google.com/spreadsheets/d/1VGmtDIyKCG89Dlo__Zq_AoEb6Raa1cJs_9P6Nwelejw/edit#gid=444938247)

2) změna na:

12.1. Seznamy - Michal B. - stejné
19.1. Místo hry, mohl by mít @encukou "Spolupráce a OpenSource", prosím? 
26.1. Procvičovací hra Pong - Oskar? @asgeirrr 
2.2. Slovníky I
9.2. Slovníky II
16.2. Grafika
23.2. Třídy

Byla bych ráda, za případné schválení nového programu či odmítnutí, abych to mohla do tabulky zapsat.

**Comment by encukou** [comment]
Pong je v programu PyLadies taky, u Grafiky: http://pyladies.cz/v1/s012-pyglet/pong.py - tam je spíš jako domácí aktivita (čtení kódu, který napsal někdo jiný), ale dá se i udělat tahle hra _místo_ normální lekce Grafiky. Nejsou tam slovníky, takže může být před nima.

Takže potom by grafika byla sfouknutá, a spíš bych dal 16.2. Třídy I a 23. 2. Třídy II. Jinak OK, Spolupráci si klidně vezmu.

**Comment by lspdv** [comment]
Místo grafiky? Já bych grafiku i nechala? Byla to sranda a jsou u ní vidět výsledky. Tohle bylo myšleno místo Solitaire. To, že to nějak vypadá měl být příjemný motivační bonus.

:-)

**Comment by encukou** [comment]
No jo, jenomže k tomu buď grafiku potřebuješ umět, nebo ji tě to naučí :)
Jedimé co k tomu Grafika přidává je vykreslování obrázků (místo obdélníčků)...

**Comment by Aprillion** [comment]
ja v zasade suhlasim ak sa updatuje program. 

a uz mam aj viac casu na pripravu tak ak na niektory termin nie je hlavny kouc mozem byt ja.. len neviem ci sa to nebude moc striedat

**Comment by asgeirrr** [comment]
Teď jsem to procházel a osobně si myslím, že učit se nové věci (grafiku)
a dělat první větší věc na cca 200 řádek nezvládneme za jednu hodinu.
Ale mohlo by fungovat nejdřív udělat grafiku a pak na dalším srazu
udělat první větší věc, tedy Pong a využít, co jsme se naučili v
předchozí hodině. Obě hodiny by myslím byly interaktivní a holky by se
hodně naučili. Moho k Pongu připravit materiály.

Myslím, že tohle pořadí dává smysl:

121 Seznamy - Michal B - stejné

191 "Spolupráce a OpenSource", prosím? @encukou[1]

261 Grafika @asgeirrr[2] nebo kdokoliv jiný;) 22 Procvičovací hra Pong
@asgeirrr[3]

92 Slovníky I

Co myslíte vy?

Dne St, 6. leden 2016 v 19:14 h uživatel Peter Hozák napsal:

> ja v zasade suhlasim ak sa updatuje program.
> 
> a uz mam aj viac casu na pripravu tak ak na niektory termin nie je
> hlavny kouc mozem byt ja.. len neviem ci sa to nebude moc striedat
> 
> — Reply to this email directly or view it on GitHub[4].

Links:
1. https://github.com/encukou
2. https://github.com/asgeirrr
3. https://github.com/asgeirrr
4. https://github.com/PyLadiesCZ/documents/issues/20#issuecomment-169408209

**Comment by asgeirrr** [comment]
Kód na Pong máme od Petra, musel bych "jen" sepsat materiály.

Dne So, 9. leden 2016 v 21:20 h uživatel Oskar Hollmann napsal:

> Teď jsem to procházel a osobně si myslím, že učit se nové věci
> (grafiku) a dělat první větší věc na cca 200 řádek nezvládneme za
> jednu hodinu. Ale mohlo by fungovat nejdřív udělat grafiku a pak na
> dalším srazu udělat první větší věc, tedy Pong a využít, co jsme se
> naučili v předchozí hodině. Obě hodiny by myslím byly interaktivní a
> holky by se hodně naučili. Moho k Pongu připravit materiály.
> 
> Myslím, že tohle pořadí dává smysl:
> 
> 121 Seznamy - Michal B - stejné 191 "Spolupráce a OpenSource", prosím?
> @encukou[1] 261 Grafika @asgeirrr[2] nebo kdokoliv jiný;) 22
> Procvičovací hra Pong @asgeirrr[3] 92 Slovníky I
> 
> Co myslíte vy?
> 
> Dne St, 6. leden 2016 v 19:14 h uživatel Peter Hozák napsal:
> 
> > ja v zasade suhlasim ak sa updatuje program.
> > 
> > a uz mam aj viac casu na pripravu tak ak na niektory termin nie je
> > hlavny kouc mozem byt ja.. len neviem ci sa to nebude moc striedat
> > 
> > — Reply to this email directly or view it on GitHub[4].

Links:
1. https://github.com/encukou
2. https://github.com/asgeirrr
3. https://github.com/asgeirrr
4. https://github.com/PyLadiesCZ/documents/issues/20#issuecomment-169408209

**Comment by lspdv** [comment]
Me se tento napad i presun zamlouva! :-) dekuju Oskare

Odesláno z iPadu
1. 1. 2016 v 21:21, Oskar Hollmann notifications@github.com:
