### ISSUE TITLE
Články a blogísky

### ISSUE THREAD

**Issue by zuzejk** [PyLadiesCZ/documents#23]
chceme být slavní, nebo to ponecháme zatím jiným? :cactus: 
aktuálně koukám v mailu na nabídku na článek na webu http://www.helloworld.cz/category/holky_v_it/

**Comment by zuzejk** [comment]
četla jsem, co tam mají za další články, a celkem se mi to zamlouvá. Nicméně nevím, jak bychom to kdyžtak uchopili...

**Comment by honzajavorek** [comment]
Z hlediska publikace vidím dvě cesty:
- Publikace vlastních článků (třeba o novém běhu, o změnách v organizaci apod.)
- Publikace "PR" článků o tom, že existují PyLadies, na jiných webech.

helloworld.cz a další jsou ten druhý případ a nechám na vás, co s tím vymyslíte. Co se týče prvního případu, připravuji blogísek pro celý český Python, který by jel na blog.python.cz. Byl bych rád, kdybych se mohl přimluvit za to, aby tam vlastní PyLadies články vycházely dohromady se vším ostatním, tzn. aby se případně nezakládal teď ani v blízké budoucnosti samostatný PyLadies blog. Python blog bude na GitHubu a otevřený pro publikaci komukoliv pomocí Pull Requestu.

**Comment by asgeirrr** [comment]
Proč ne, jen ať se o naší zasluzne činnosti píše;)

**Comment by encukou** [comment]
Myslím že tohle se rozjelo; můžeme zavřít?

**Comment by honzajavorek** [comment]
No já bych neřekl, že **se** to rozjelo, ale že to @lspdv rozjela :) Jinak se zavřením souhlasím. Akorát teda ještě neumíme ty PR články jinam o tom, co jsou PyLadies, ale je otázka, jestli to potřebujeme. A časem se k tomu asi stejně dostaneme.
