### ISSUE TITLE
Samolepky

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#5]
@lspdv:

Zajistit tisk samolepek pro PyLadies kurzy

**Vyřešit:** Získat soubory s návrhy samolepek a zajistit tisk, poté dát PyLady

**Comment by encukou** [comment]
Oficiální samolepky jsou odtud: https://www.stickermule.com/ca/user/1070441144/stickers, takže spíš je jen potřeba domluvit množstevní a PyLadies-ovní slevu :)
Souvisí s #19

**Comment by lspdv** [comment]
Slevu?! Asi to budu zarizovat ja, tak prosim o nejake blizsi informace. 

Odesláno z iPadu
1. 12. 2015 v 21:59, Petr Viktorin notifications@github.com:

**Comment by encukou** [comment]
Bližší informace nemám, ale příslušné kontakty snad vyplynou z #19. Samolepky co jsem rozdával jsem dostal na EuroPythonu od Lynn Root.

**Comment by lspdv** [comment]
Jo, uz se do toho dostavam, jak jsi to myslel se slevou. :-) 
To poresim. Mohlo by byt i vice moznosti jak to udelat jednoduseji nez pres dovoz z ciziny. Tak se zkusim probojovat pres tu Lynn ke schvaleni tisknout to v Praze a dostat se k vektorovy verzi. 
:-) dik

**Comment by lspdv** [comment]
Už mám bližší informace o samolepkách, od organizátorky Jacqueline Kazil z D.C., budu mít křivky, mám volnou ruku, nechat si to tisknout v ČR.

Tak by chtěla požádat @honzajavorek o radu. Chtěl by náš kámos Pyvec koupit samolepky pro PyLadies? Pokud ne, najdu obratem sponzora. Pokud by Pyvec chtěl, mám dobrou firmu, co dělá pěkné samolepky za rozumnou cenu, spolupracuji s nimi na více projektech, tak by třeba i kluci na Pyvu mohli čestně nosit samolepky (Pyvce, ne Pyladies) :-)) Dík.

**Comment by encukou** [comment]
Mám od Red Hatu slíbené peníze na podobné účely. Jen to bylo před pár lety (nedostal jsem se k organizaci takovýchhle odboček), můžu se zeptat jestli to pořád platí, a na podmínky (nevím třeba jestli nebudou chtít sami vybrat firmu pro tisk).

**Comment by lspdv** [comment]
Pokud budou chtít vybrat sami firmu, tak mi to vůbec nevadí, vzhledem k
tomu, že to případně zasponzorují. :-))) Děkuji moc Petře, že se zeptáš.

Případně ale má snaha pro Pyvec i tak platí, kdyby se PyLadies
případně zařizovaly přes samolepkáře od RedHat, tak si stále mohu vzít na
starost Pyvec tady v Praze.

Dne 14. ledna 2016 10:21 Petr Viktorin notifications@github.com napsal(a):

**Comment by lspdv** [comment]
A hlavne se mi libi, ze RedHat by pripadne jiste mel kapacitu na obe mesta a tim by se Ti Petre smazal rest, respektive organizatorkam z Brna ;-) a to me na tom bavi. Tak doufam, ze to vyjde ;-) 

Odesláno z iPadu
1. 1. 2016 v 10:21, Petr Viktorin notifications@github.com:

**Comment by honzajavorek** [comment]
Na větší věci bych se zeptal, ale samolepky určitě zatáhnout můžem :) cc @martinbilek

**Comment by martinbilek** [comment]
Jasně, samolepky zatáhnout můžem :-) Ideálně, když mi jen před závaznou objednávkou dáte vědět, kolik to bude cca stát, platbu ideálně vyřešit převodem - buď předem na zálohovou fakturu nebo na fakturu normálně.

P.S.: Fakturu vystavit pls na Pyvec, viz. http://pyvec.org/o-nas/

**Comment by encukou** [comment]
Spočítejme dneska kolik jich bude potřeba.

**Comment by lspdv** [comment]
Hotovo. Spocitano. Vytisknuto. Zaplaceno.

**Comment by encukou** [comment]
Verča je nejlepší!
