### ISSUE TITLE
Místo konání srazů

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#6]
@lspdv:

V CZ.NIC (u náměstí Jiřího z Poděbrad) mají moc pěknou Akademii, studovnu pro cca 20 posluchačů a take mají pěknou menší a komornější zasedačku, kde se dá sedět dokola kolem stolu, jakožto máme tak i teď v ManPower. Nabídli nám ochotně tyto prostory a my bychom nabídku rády využily. Na poradě holek jsme se shodly, že tuto možnost využijeme od případného třetího běhu. Tento doděláme ve Florentinu, abychom to holkám každé úterý večer nekomplikovaly. V příštím běhu již holky budou vědět, do čeho půjdou a jistě jim srazy na Jiřího z Poděbrad nebudou dělat komplikace.

**Comment by lspdv** [comment]
S potesenim oznamuji, ze nasledujici Prazsky beh se uskutecni v prostorach CZ.NIC. Domluveno.

**Comment by honzajavorek** [comment]
Jooooo!

**Comment by asgeirrr** [comment]
Skvělá zpráva:) Dohadovala jsi už s nima konkrétní termín nebo zatím ne? Myslím, že zachovat tradiční úterý by bylo dobré. Koučové jsou na to už zvyklí. A já i nějakým zájemkyním říkal, že jsme to mívali v úterý...

Dne Pá, 18. březen 2016 v 13:12 h uživatel Honza Javorek napsal:

> Jooooo!
> 
> On 18 Mar 2016 12:59 p.m., "Veronika" notifications@github.com wrote:
> 
> Closed #6 https://github.com/PyLadiesCZ/documents/issues/6.
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly or view it on GitHub
> 
> https://github.com/PyLadiesCZ/documents/issues/6#event-594766097
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/PyLadiesCZ/documents/issues/6#issuecomment-198326594

**Comment by lspdv** [comment]
Ahoj je to na 100% úterý 18 - 20

2016-03-20 11:38 GMT+01:00 Oskar Hollmann notifications@github.com:

> Skvělá zpráva:) Dohadovala jsi už s nima konkrétní termín nebo zatím ne?
> Myslím, že zachovat tradiční úterý by bylo dobré. Koučové jsou na to už
> zvyklí. A já i nějakým zájemkyním říkal, že jsme to mívali v úterý...
> 
> Dne Pá, 18. březen 2016 v 13:12 h uživatel Honza Javorek napsal:
> 
> > Jooooo!
> >
