### ISSUE TITLE
Vyzkoušet materiály pro všechny platformy

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#7]
@lspdv:

Nejčastěji byl problém s Windows, někdy s MacOS (viz Grafika na Verčině MacBooku). Hlavní kouč musí mít v Windows v malíčku -- instalaci Pythonu, Unicode znaky, nepoužitelný terminál a práci s Gitem (hlavně kterou instalačku použít).

**Vyřešit:** Sepsat manuál koučů. 
**Vyřešit:** Navrhnout možnost, jak takovýmto problémům předejít sjednocením a odhlasovat to.

**Comment by encukou** [comment]
Je tohle stále problém?

@frenzymadness, byl to problém v Ostravě?

**Comment by lspdv** [comment]
Zavrit myslim si :-)

Dne čtvrtek 2. února 2017 Petr Viktorin <notifications@github.com>
napsal(a):

**Comment by encukou** [comment]
Kdyžtak to, @frenzymadness, otevři znova.
