### ISSUE TITLE
Dělat úlohy maximálně multiplatformní

### ISSUE THREAD

**Issue by honzajavorek** [PyLadiesCZ/documents#8]
@lspdv:

Různé instrukce pro různé systémy jsou pro holky zbytečně matoucí a hlavnímu koučovi ubírají čas na vysvětlení samotného problému. Do příštího kurzu by bylo dobré zvážit použití Minicondy a IPython Notebooku, což jsou nástroje, které se chovají na všech platformách stejně (teoreticky) a na Windows řadu věcí zjednodušují (hlavně instalaci knihoven jako je NumPy či SciPy, které mohou být snadno použity pro zpestření úkolů). Instrukce by pak mohly být pro různé platformy podobnější.

**Vyřešit:** Návrh možností takových nástrojů a poté odhlasovat, co se bude používat.

**Comment by encukou** [comment]
Radši bych viděl lepší instrukce pro jednotlivé platformy – NumPy i SciPy nainstalovat jdou, a snad i celkem snadno, jen je potřeba vědět jak na to. Radši bych řešil tohle, než vytvářel normalizované školní prostředí, které se po skončení kurzu zahodí.

**Comment by asgeirrr** [comment]
Numpy a SciPy jdou na WIndows nainstalovat velmi těžko, je potřeba mít
kompilátor, což ve Windows znamená nainstalovat Visual Studio. V tomhle
ohledu by nám pomohla Miniconda[1], to je jen pohodlný nástroj pro
instalaci Python knihoven na Windows a holky ho pak mohou používat bez
problémů dál na dalších projektech. Na začátku by se místo Pythonu
instalovala Miniconda, která má Python v sobě (i pip a další tradiční
Python nástroje).

Dne So, 12. prosinec 2015 v 21:37 h uživatel Petr Viktorin napsal:

> Radši bych viděl lepší instrukce pro jednotlivé platformy – NumPy i
> SciPy nainstalovat jdou, a snad i celkem snadno, jen je potřeba vědět
> jak na to. Radši bych řešil tohle, než vytvářel normalizované školní
> prostředí, které se po skončení kurzu zahodí.
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. http://conda.pydata.org/miniconda.html
2. https://github.com/PyLadiesCZ/documents/issues/8#issuecomment-164188998

**Comment by encukou** [comment]
Tohle nefunguje?

```
pip install -i https://pypi.binstar.org/carlkl/simple numpy
pip install -i https://pypi.binstar.org/carlkl/simple scipy
```

viz https://github.com/numpy/numpy/issues/5479

**Comment by asgeirrr** [comment]
Tohle asi ano, na binstar je předpokládám binárka, ale určitě nefunguje
pip install numpy, to potřebuje na Windows Visual Studio a na Macu
Command Line Tools.

Miniconda je balíčkovací systém, kde jsou všechny tyhle ikonické
knihovny už zkompilované pro všechny platformy (tzn. i v Linuxu je
instalace rychlejší než instalace pipem, která to kompiluje). Kopíruje
rozhraní pipu, takže člověk dá jednoduše conda install numpy a je to.
Možná je to o něco jednodušší než

pip install -i https://pypi.binstar.org/carlkl/simple numpy

ale už je to skoro jedno. Dobrý nápad s tím binstar, o tom jsem nevěděl.

Dne So, 12. prosinec 2015 v 22:42 h uživatel Petr Viktorin napsal:

> Tohle nefunguje?
> 
> pip install -i https://pypi.binstar.org/carlkl/simple numpy
> pip install -i https://pypi.binstar.org/carlkl/simple scipy
> 
> viz numpy/numpy#5479[1]
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. https://github.com/numpy/numpy/issues/5479
2. https://github.com/PyLadiesCZ/documents/issues/8#issuecomment-164195801

**Comment by Aprillion** [comment]
diskusia o git bash pre windows nejak dopadla? plus rovnake prikazy ako linux, minus ze sa nenaucia windowsove prikazy.. aj ked neviem na co su dobre ak sa da pouzit git bash ;)

**Comment by encukou** [comment]
Git Bash příště zkusím, pokud mě do té doby nějaký windowsář nepřesvědčí že má cenu učit Windowsí příkazovou řádku.
(Další plus je to, že na prvním sraze nainstalujeme všechno potřebné – Python i Git.)

**Comment by Aprillion** [comment]
ja keby som o

**Comment by Aprillion** [comment]
..ja keby som o git bash vedel skor tak nemusim riesit windowsove vobec.

najdolizejsia cesta asi /c/Users/... lebo ~ (home) sa potom neda najst v Exploreri tak lahko

**Comment by encukou** [comment]
Tohohle se nikdo nechytil, a já to udělat neplánuju. (Jupyter Notebook a NumPy se navíc teď instalují docela hezky, a od Pythonu 3.6 by měl fungovat i ve Windows Unicode.)

Případné zájemce prosím aby vyzkoušeli na některém kurzu/workshopu, nebo začali pracovat na PR na existující materiály. Rád pomůžu, ale nebudu to vést.

V případě potřeby to otevři znovu.
